// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDWRx4BYk0bAG0DBT4S9Fx-RB1LwFbnQOk',
    appId: '1:1008245399655:web:aec12b6b623b206efb34c2',
    messagingSenderId: '1008245399655',
    projectId: 'panchayatbase-2ea49',
    authDomain: 'panchayatbase-2ea49.firebaseapp.com',
    storageBucket: 'panchayatbase-2ea49.firebasestorage.app',
    measurementId: 'G-NL1CE01MBB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBiXFXFOJGJtdGb-mr-8JDW38rU1n3cGYY',
    appId: '1:1008245399655:android:48391f17c2d2fce8fb34c2',
    messagingSenderId: '1008245399655',
    projectId: 'panchayatbase-2ea49',
    storageBucket: 'panchayatbase-2ea49.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAmv6UylXhBvF5PvUpJ0Y9Uoj-rCs819us',
    appId: '1:1008245399655:ios:cf34396c744ab512fb34c2',
    messagingSenderId: '1008245399655',
    projectId: 'panchayatbase-2ea49',
    storageBucket: 'panchayatbase-2ea49.firebasestorage.app',
    iosBundleId: 'com.example.eGovernance',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAmv6UylXhBvF5PvUpJ0Y9Uoj-rCs819us',
    appId: '1:1008245399655:ios:cf34396c744ab512fb34c2',
    messagingSenderId: '1008245399655',
    projectId: 'panchayatbase-2ea49',
    storageBucket: 'panchayatbase-2ea49.firebasestorage.app',
    iosBundleId: 'com.example.eGovernance',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDWRx4BYk0bAG0DBT4S9Fx-RB1LwFbnQOk',
    appId: '1:1008245399655:web:44c75ed196e504b7fb34c2',
    messagingSenderId: '1008245399655',
    projectId: 'panchayatbase-2ea49',
    authDomain: 'panchayatbase-2ea49.firebaseapp.com',
    storageBucket: 'panchayatbase-2ea49.firebasestorage.app',
    measurementId: 'G-EQ9VV21FQT',
  );
}
